[package]
name = "neuron-test"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"